// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD01V_Ird4_e_7fV5LXXbJIDGUgAvyCs58',
    appId: '1:266297276876:web:0b2d019aa007e53060c569',
    messagingSenderId: '266297276876',
    projectId: 'caredb',
    authDomain: 'caredb.firebaseapp.com',
    storageBucket: 'caredb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkMGLY76fBQtcEbXYGUkXQnULNxKShGmQ',
    appId: '1:266297276876:android:636f7be3004e2fcb60c569',
    messagingSenderId: '266297276876',
    projectId: 'caredb',
    storageBucket: 'caredb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb3LwIsAq6sIfesM4JjMaCL2L6oswEhXs',
    appId: '1:266297276876:ios:74264a3cd0a2646b60c569',
    messagingSenderId: '266297276876',
    projectId: 'caredb',
    storageBucket: 'caredb.firebasestorage.app',
    iosBundleId: 'com.example.caretutors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb3LwIsAq6sIfesM4JjMaCL2L6oswEhXs',
    appId: '1:266297276876:ios:74264a3cd0a2646b60c569',
    messagingSenderId: '266297276876',
    projectId: 'caredb',
    storageBucket: 'caredb.firebasestorage.app',
    iosBundleId: 'com.example.caretutors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD01V_Ird4_e_7fV5LXXbJIDGUgAvyCs58',
    appId: '1:266297276876:web:79ce945e42ce358f60c569',
    messagingSenderId: '266297276876',
    projectId: 'caredb',
    authDomain: 'caredb.firebaseapp.com',
    storageBucket: 'caredb.firebasestorage.app',
  );
}
